using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using SpoolManager.Shared.Models;

namespace SpoolManager.Infrastructure.Services;

public interface ISlicerExportService
{
    string ExportToOrcaSlicer(SlicerProfile profile, FilamentMaterial material, string? printerName = null);
    string ExportToPrusaSlicer(SlicerProfile profile, FilamentMaterial material, string? printerName = null);
}

public class SlicerExportService : ISlicerExportService
{
    private static readonly Dictionary<string, string> OrcaInheritsMap = new(StringComparer.OrdinalIgnoreCase)
    {
        ["PLA"] = "Generic PLA",
        ["PETG"] = "Generic PETG",
        ["ABS"] = "Generic ABS",
        ["ASA"] = "Generic ASA",
        ["TPU"] = "Generic TPU",
        ["Nylon"] = "Generic PA",
        ["PA"] = "Generic PA",
        ["PC"] = "Generic PC",
        ["PVA"] = "Generic PVA",
        ["HIPS"] = "Generic HIPS",
        ["PP"] = "Generic PP",
        ["PET"] = "Generic PET"
    };

    public string ExportToOrcaSlicer(SlicerProfile profile, FilamentMaterial material, string? printerName = null)
    {
        var inherits = OrcaInheritsMap.GetValueOrDefault(material.Type, $"Generic {material.Type}");

        var obj = new Dictionary<string, object>
        {
            ["type"] = "filament",
            ["name"] = $"{profile.Name} @SpoolHero",
            ["inherits"] = inherits,
            ["from"] = "User",
            ["filament_type"] = new[] { material.Type }
        };

        AddIfNotNull(obj, "nozzle_temperature", profile.NozzleTemp);
        AddIfNotNull(obj, "nozzle_temperature_initial_layer", profile.NozzleTempInitialLayer);
        AddIfNotNull(obj, "bed_temperature", profile.BedTemp);
        AddIfNotNull(obj, "bed_temperature_initial_layer", profile.BedTempInitialLayer);
        AddIfNotNull(obj, "hot_plate_temp", profile.BedTemp);
        AddIfNotNull(obj, "hot_plate_temp_initial_layer", profile.BedTempInitialLayer);
        AddIfNotNull(obj, "chamber_temperature", profile.ChamberTemp);
        AddIfNotNullDecimal(obj, "filament_flow_ratio", profile.FilamentFlowRatio);
        AddIfNotNullDecimal(obj, "pressure_advance", profile.PressureAdvance);
        AddIfNotNull(obj, "fan_min_speed", profile.FanMinSpeed);
        AddIfNotNull(obj, "fan_max_speed", profile.FanMaxSpeed);
        AddIfNotNull(obj, "close_fan_the_first_x_layers", profile.FanDisableFirstLayers);
        AddIfNotNull(obj, "overhang_fan_speed", profile.OverhangFanSpeed);
        AddIfNotNullDecimal(obj, "filament_retraction_length", profile.RetractionLength);
        AddIfNotNull(obj, "filament_retraction_speed", profile.RetractionSpeed);
        AddIfNotNullDecimal(obj, "filament_z_hop", profile.ZHop);
        AddIfNotNullDecimal(obj, "filament_max_volumetric_speed", profile.MaxVolumetricSpeed);

        if (!string.IsNullOrEmpty(profile.FilamentStartGcode))
            obj["filament_start_gcode"] = new[] { profile.FilamentStartGcode };
        if (!string.IsNullOrEmpty(profile.FilamentEndGcode))
            obj["filament_end_gcode"] = new[] { profile.FilamentEndGcode };

        obj["compatible_printers"] = printerName != null ? new[] { printerName } : Array.Empty<string>();

        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };
        return JsonSerializer.Serialize(obj, options);
    }

    public string ExportToPrusaSlicer(SlicerProfile profile, FilamentMaterial material, string? printerName = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# generated by SpoolHero");
        if (printerName != null)
            sb.AppendLine($"# printer: {printerName}");
        sb.AppendLine($"[filament:{profile.Name} @SpoolHero]");
        sb.AppendLine($"filament_type = {material.Type}");

        AppendIfNotNull(sb, "temperature", profile.NozzleTemp);
        AppendIfNotNull(sb, "first_layer_temperature", profile.NozzleTempInitialLayer);
        AppendIfNotNull(sb, "bed_temperature", profile.BedTemp);
        AppendIfNotNull(sb, "first_layer_bed_temperature", profile.BedTempInitialLayer);
        AppendIfNotNullDecimal(sb, "filament_retract_length", profile.RetractionLength);
        AppendIfNotNull(sb, "filament_retract_speed", profile.RetractionSpeed);
        AppendIfNotNullDecimal(sb, "filament_retract_lift", profile.ZHop);
        AppendIfNotNull(sb, "min_fan_speed", profile.FanMinSpeed);
        AppendIfNotNull(sb, "max_fan_speed", profile.FanMaxSpeed);
        AppendIfNotNull(sb, "disable_fan_first_layers", profile.FanDisableFirstLayers);
        AppendIfNotNull(sb, "bridge_fan_speed", profile.OverhangFanSpeed);
        AppendIfNotNullDecimal(sb, "extrusion_multiplier", profile.FilamentFlowRatio);

        if (material.DensityGCm3.HasValue)
            sb.AppendLine($"filament_density = {material.DensityGCm3.Value.ToString("F2", CultureInfo.InvariantCulture)}");
        if (material.PricePerKg.HasValue)
            sb.AppendLine($"filament_cost = {material.PricePerKg.Value.ToString("F2", CultureInfo.InvariantCulture)}");

        return sb.ToString();
    }

    private static void AddIfNotNull(Dictionary<string, object> obj, string key, int? value)
    {
        if (value.HasValue)
            obj[key] = new[] { value.Value.ToString(CultureInfo.InvariantCulture) };
    }

    private static void AddIfNotNullDecimal(Dictionary<string, object> obj, string key, decimal? value)
    {
        if (value.HasValue)
            obj[key] = new[] { value.Value.ToString("G", CultureInfo.InvariantCulture) };
    }

    private static void AppendIfNotNull(StringBuilder sb, string key, int? value)
    {
        if (value.HasValue)
            sb.AppendLine($"{key} = {value.Value}");
    }

    private static void AppendIfNotNullDecimal(StringBuilder sb, string key, decimal? value)
    {
        if (value.HasValue)
            sb.AppendLine($"{key} = {value.Value.ToString("G", CultureInfo.InvariantCulture)}");
    }
}
